//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_0o9ygclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_EDFE69E4_edfe69e4_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0pWNA8lgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/initiate_project_D9C03857_d9c03857_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0pJ_xslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_91569239_91569239_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sluQslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/agree_technical_approach_350ADF37_350adf37_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_92eadf8b_Activity.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_92eadf8b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/develop_architecture_AF0A71D5_af0a71d5_Activity.jpeg"
contentPage.processPage.imageFiles["_0sx7islgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_architecture_AF0A71D5_af0a71d5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_h2-iAfimEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_633E2E80_633e2e80_Activity.jpeg"
contentPage.processPage.imageFiles["_h2-iAfimEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_633E2E80_633e2e80_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0nz79clgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/test_solution_59590D2E_59590d2e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0nJNkslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/plan_manage_iteration_D46BADD3_d46badd3_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaA,_0qxwYclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_ACB4F513_594f0c8b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaA,_0q33AclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_2F27034C_dbc11ac4_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rilYclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/Test Solution_508027B8_8add021a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaA,_jLaKwP77Edm1zMZYtD3GjAActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_E0BEBBF4_76d95d50_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaA,_0okw8clgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_797D013F_f97a29b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_y-3IretQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/test_solution_F0E4EA46_d4076c48_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/elaboration_phase_iteration_427C4DE0_2ad6160e_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_WrXvwPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_10d5060a_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_WrXvwPinEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_10d5060a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_y-k0bOtQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_4EF10D2F_32138f31_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0ruyoclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_824699A3_bca37405_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_y_PjTOtQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_2F5F2C64_1281ae66_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rcewclgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_6c99eaf1_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rcewclgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_6c99eaf1_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaA,_0oreoclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/agree_technical_approach_944692EF_2a61344b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/inception_phase_iteration_648AE2DA_4ce4ab08_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaA,_0qrpwslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/test_solution_B2F7A244_5f91b9bc_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_xupMvxOKEduCNqgZdt_OaA,_0oSdE8lgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/initiate_project_ED8BD86C_83a679c8_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rWYIslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_84F991D7_bf566c39_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_TAVx0CliEdqjQsaFX0CJTwActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_7DF42BFF_b8510661_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_eE5nEUbpEduLBN1xMBngqwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_E2BECCD3_c5e14ed5_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_nen3UexwEduRmOwej6GrogActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_4DCE9885_30f11a87_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaA,_nen3UexwEduRmOwej6GrogActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_4DCE9885_30f11a87_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rcewclgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/develop_architecture_4C24F4D9_8681cf3b_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_0Spa4BOKEduCNqgZdt_OaA,_0rcewclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_architecture_4C24F4D9_8681cf3b_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaA,_0DMlYPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_EE81900_bb823078_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaA,_0DMlYPinEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_EE81900_bb823078_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_467NIhOKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/transition_phase_iteration_31BFECF6_1a19b524_Activity.jpeg"
contentPage.processPage.imageFiles["_0uyGoMlgEdmt3adZL5Dmdw,_3CqrAROKEduCNqgZdt_OaAActivity"]="./../../openup/deliveryprocesses/resources/construction_phase_iteration_A276D580_8ad09dae_Activity.jpeg"
contentPage.processPage.imageFiles["_BgndgTzkEeir67KZWdm-8wActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Construction Phase_379E171D_379e171d_Activity.jpeg"
contentPage.processPage.imageFiles["_BgndgTzkEeir67KZWdm-8wActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Construction Phase_379E171D_379e171d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_PZiY4USqEeiiE7_Qi20MVAActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Elaboration Phase_E9D21C8D_e9d21c8d_Activity.jpeg"
contentPage.processPage.imageFiles["_PZiY4USqEeiiE7_Qi20MVAActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Elaboration Phase_E9D21C8D_e9d21c8d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_hMCeQUS3EeiiE7_Qi20MVAActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Inception Phase_A5F0C89F_a5f0c89f_Activity.jpeg"
contentPage.processPage.imageFiles["_hMCeQUS3EeiiE7_Qi20MVAActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Inception Phase_A5F0C89F_a5f0c89f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_VJjgoUSzEeiiE7_Qi20MVAActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Transistion Phase_E4AE2C92_e4ae2c92_Activity.jpeg"
contentPage.processPage.imageFiles["_VJjgoUSzEeiiE7_Qi20MVAActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Transistion Phase_E4AE2C92_e4ae2c92_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_Uc2140mZEei8Md6BW_mwcwActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Inception Phase Iteration_9CD6628D_11564f12_Activity.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_Uc2140mZEei8Md6BW_mwcwActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Inception Phase Iteration_9CD6628D_11564f12_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_RcJd8EmZEei8Md6BW_mwcwActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Elaboration Phase Iteration_6999839C_de197021_Activity.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_RcJd8EmZEei8Md6BW_mwcwActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Elaboration Phase Iteration_6999839C_de197021_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_SX4GYEmZEei8Md6BW_mwcwActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Construction Phase Iteration_882558A8_fca5452d_Activity.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_SX4GYEmZEei8Md6BW_mwcwActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Construction Phase Iteration_882558A8_fca5452d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_Uc4EAkmZEei8Md6BW_mwcwActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Transistion Phase Iteration_FF8582D_847844b2_Activity.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcw,_Uc4EAkmZEei8Md6BW_mwcwActivityDetail"]="./../../web-checkers-process/capabilitypatterns/resources/Transistion Phase Iteration_FF8582D_847844b2_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_ONfJkUmZEei8Md6BW_mwcwActivity"]="./../../web-checkers-process/capabilitypatterns/resources/Web Checkers Process_738FA131_738fa131_Activity.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_jLaKwP77Edm1zMZYtD3GjAActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_E0BEBBF4_8a1fe38e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_0okw8clgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_797D013F_22de28d9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_0oSdE8lgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/initiate_project_ED8BD86C_96ed0006_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/inception_phase_iteration_C2188B46_c2188b46_Activity.jpeg"
contentPage.processPage.imageFiles["_0o3r4slgEdmt3adZL5Dmdw,_0oreoclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/agree_technical_approach_944692EF_3da7ba89_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rWYIslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_84F991D7_b1d94938_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0ruyoclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_824699A3_af265104_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_TAVx0CliEdqjQsaFX0CJTwActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_7DF42BFF_aad3e360_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rcewclgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_a7657af0_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rcewclgEdmt3adZL5Dmdw,_bWELsd1qEduavbdP4P0fvwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_436ECE62_a7657af0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rilYclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/Test Solution_508027B8_7d5fdf19_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/elaboration_phase_iteration_97E7400D_97e7400d_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rcewclgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/develop_architecture_4C24F4D9_7904ac3a_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_0rcewclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_architecture_4C24F4D9_7904ac3a_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_WrXvwPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_357e309_Activity.jpeg"
contentPage.processPage.imageFiles["_0sTaYMlgEdmt3adZL5Dmdw,_WrXvwPinEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_D6782BA8_357e309_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRgActivity"]="./../../openup/capabilitypatterns/resources/construction_phase_iteration_FB82CA56_fb82ca56_Activity.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_y-3IretQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/test_solution_F0E4EA46_dba820f0_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_y_PjTOtQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_2F5F2C64_1a22630e_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_y-k0bOtQEdqc1LGhiSPqRgActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_4EF10D2F_39b443d9_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_nen3UexwEduRmOwej6GrogActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_4DCE9885_3891cf2f_Activity.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_nen3UexwEduRmOwej6GrogActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_4DCE9885_3891cf2f_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_y-3IrutQEdqc1LGhiSPqRg,_eE5nEUbpEduLBN1xMBngqwActivityDetail"]="./../../openup/capabilitypatterns/resources/identify_and_refine_requirements_E2BECCD3_cd82037d_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0DMlYPinEdmugcVr9AdHjQActivity"]="./../../openup/capabilitypatterns/resources/develop_solution_EE81900_51153c26_Activity.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0DMlYPinEdmugcVr9AdHjQActivityDetail"]="./../../openup/capabilitypatterns/resources/develop_solution_EE81900_51153c26_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5DmdwActivity"]="./../../openup/capabilitypatterns/resources/transition_phase_iteration_87676AD2_87676ad2_Activity.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0q33AclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/manage_iteration_2F27034C_71542672_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0qxwYclgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/ongoing_tasks_ACB4F513_eee21839_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_0rQRgMlgEdmt3adZL5Dmdw,_0qrpwslgEdmt3adZL5DmdwActivityDetail"]="./../../openup/capabilitypatterns/resources/test_solution_B2F7A244_f524c56a_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_ukbHgL-EEdqb7N6KIeDL8Q"] = ["Outline the Architecture","openup/capabilitypatterns/outline_the_architecture_B7FD36D1.html"];
contentPage.processPage.elementUrls["_-YrHMFY4EdqI9sTOt2pjHw"] = ["Implementation","openup/capabilitypatterns/implementation_7F349488.html"];
contentPage.processPage.elementUrls["_Y42y8L-EEdqb7N6KIeDL8Q"] = ["Find and Outline Requirements","openup/capabilitypatterns/find_and_outline_requirements_24FC0F26.html"];
contentPage.processPage.elementUrls["_0q33AclgEdmt3adZL5Dmdw"] = ["Plan and Manage Iteration","openup/capabilitypatterns/manage_iteration_2F27034C.html"];
contentPage.processPage.elementUrls["_Uc3c-kmZEei8Md6BW_mwcw"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_E6E84C00.html"];
contentPage.processPage.elementUrls["_9JHQUCNDEdy8morYWHvpBw"] = ["Developer","openup/capabilitypatterns/developer_1F4B3044.html"];
contentPage.processPage.elementUrls["_eFeO00bpEduLBN1xMBngqw"] = ["Use-Case Model","openup/capabilitypatterns/uc_model_AD897B15.html"];
contentPage.processPage.elementUrls["_mz-XIES3EeiiE7_Qi20MVA"] = ["Team Information","web-checkers-process/capabilitypatterns/team_information_F4B44168.html"];
contentPage.processPage.elementUrls["_Uc3c_kmZEei8Md6BW_mwcw"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_4B66760E.html"];
contentPage.processPage.elementUrls["_SX4td0mZEei8Md6BW_mwcw"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_836E08D5.html"];
contentPage.processPage.elementUrls["_XlvPMESzEeiiE7_Qi20MVA"] = ["Developer","web-checkers-process/capabilitypatterns/developer_D95398E1.html"];
contentPage.processPage.elementUrls["_Uc2160mZEei8Md6BW_mwcw"] = ["Slack Team","web-checkers-process/capabilitypatterns/slack_team_25FA26CB.html"];
contentPage.processPage.elementUrls["_RcKsE0mZEei8Md6BW_mwcw"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_BBB059C8.html"];
contentPage.processPage.elementUrls["_eE5nEUbpEduLBN1xMBngqw"] = ["Identify and Refine Requirements","openup/capabilitypatterns/identify_and_refine_requirements_E2BECCD3.html"];
contentPage.processPage.elementUrls["_ezOKIk9DEdudU75l2xOQTw"] = ["Use Case","openup/capabilitypatterns/use_case_13ABA30F.html"];
contentPage.processPage.elementUrls["_TPsdoEmSEduO0bs89Khm8Q"] = ["Assess Results","openup/capabilitypatterns/assess_results_DB6B9448.html"];
contentPage.processPage.elementUrls["_ns48IUS3EeiiE7_Qi20MVA"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_CDC9CA09.html"];
contentPage.processPage.elementUrls["_DT8oADk-EduFTqg5hiiQIw"] = ["Analyst","openup/capabilitypatterns/analyst_FFC972FD.html"];
contentPage.processPage.elementUrls["_eFeO0EbpEduLBN1xMBngqw"] = ["Analyst","openup/capabilitypatterns/analyst_4B78B12A.html"];
contentPage.processPage.elementUrls["_eG0SoEbpEduLBN1xMBngqw"] = ["Glossary","openup/capabilitypatterns/glossary_FA2071A5.html"];
contentPage.processPage.elementUrls["_ClZPoUmaEei8Md6BW_mwcw"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_1CE75530.html"];
contentPage.processPage.elementUrls["_6Qwpgg1SEdyKD8XBf_Hbrw"] = ["Developer Test","openup/capabilitypatterns/developer_test_1277405C.html"];
contentPage.processPage.elementUrls["_CmNvAUmaEei8Md6BW_mwcw"] = ["Project Plan","web-checkers-process/capabilitypatterns/project_plan_82FE1F51.html"];
contentPage.processPage.elementUrls["_RcJd9EmZEei8Md6BW_mwcw"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_2E2B65BB.html"];
contentPage.processPage.elementUrls["_6QwpgA1SEdyKD8XBf_Hbrw"] = ["Integrate and Create Build","openup/capabilitypatterns/integrate_and_create_build_19404C36.html"];
contentPage.processPage.elementUrls["_VZk0ZBeDEduXJrZWmtC8tg"] = ["Vision","openup/capabilitypatterns/vision_EDFD76C5.html"];
contentPage.processPage.elementUrls["_CmDW8UmaEei8Md6BW_mwcw"] = ["Architecture Notebook","web-checkers-process/capabilitypatterns/architecture_notebook_A5E8F625.html"];
contentPage.processPage.elementUrls["_RcKsEUmZEei8Md6BW_mwcw"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_643D6FED.html"];
contentPage.processPage.elementUrls["_SHo94USqEeiiE7_Qi20MVA"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_5320D772.html"];
contentPage.processPage.elementUrls["_VNvacFY5EdqI9sTOt2pjHw"] = ["Vision","openup/capabilitypatterns/vision_729CA9B4.html"];
contentPage.processPage.elementUrls["_0oSdE8lgEdmt3adZL5Dmdw"] = ["Initiate Project","openup/capabilitypatterns/initiate_project_ED8BD86C.html"];
contentPage.processPage.elementUrls["_KkyzxDzkEeir67KZWdm-8w"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_C8603D62.html"];
contentPage.processPage.elementUrls["_DT8oBDk-EduFTqg5hiiQIw"] = ["Any Role","openup/capabilitypatterns/any_role_C45B551C.html"];
contentPage.processPage.elementUrls["_RcKFBUmZEei8Md6BW_mwcw"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_EF949AA3.html"];
contentPage.processPage.elementUrls["_SX4tdEmZEei8Md6BW_mwcw"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_215D3EEA.html"];
contentPage.processPage.elementUrls["_0DMlYPinEdmugcVr9AdHjQ"] = ["Develop Solution Increment","openup/capabilitypatterns/develop_solution_EE81900.html"];
contentPage.processPage.elementUrls["_SX3fUUmZEei8Md6BW_mwcw"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_807BB03C.html"];
contentPage.processPage.elementUrls["_cMHeAL-FEdqb7N6KIeDL8Q"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_BABA7963.html"];
contentPage.processPage.elementUrls["_wGeiAFY6EdqI9sTOt2pjHw"] = ["Use Case","openup/capabilitypatterns/use_case_BBBA3588.html"];
contentPage.processPage.elementUrls["_I7M_wzzkEeir67KZWdm-8w"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_EABCB458.html"];
contentPage.processPage.elementUrls["_piI90DlJEdyTZ9G7ByfQTw"] = ["Iteration Plan","openup/capabilitypatterns/iteration_plan_E494B488.html"];
contentPage.processPage.elementUrls["_C5TDEUmaEei8Md6BW_mwcw"] = ["Developer Test","web-checkers-process/capabilitypatterns/developer_test_1653E21D.html"];
contentPage.processPage.elementUrls["_DT8oBTk-EduFTqg5hiiQIw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_CEF9352C.html"];
contentPage.processPage.elementUrls["_Uc218UmZEei8Md6BW_mwcw"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_57AB012E.html"];
contentPage.processPage.elementUrls["_0nJNkslgEdmt3adZL5Dmdw"] = ["Plan and Manage Iteration","openup/capabilitypatterns/plan_manage_iteration_D46BADD3.html"];
contentPage.processPage.elementUrls["_Uc3dAEmZEei8Md6BW_mwcw"] = ["Analyst","web-checkers-process/capabilitypatterns/analyst_16C16407.html"];
contentPage.processPage.elementUrls["_Uc4EB0mZEei8Md6BW_mwcw"] = ["Developer","web-checkers-process/capabilitypatterns/developer_3D641011.html"];
contentPage.processPage.elementUrls["_C4t0QUmaEei8Md6BW_mwcw"] = ["Final Release","web-checkers-process/capabilitypatterns/final_release_237CAEDC.html"];
contentPage.processPage.elementUrls["_XlwdUkSzEeiiE7_Qi20MVA"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_F00B1772.html"];
contentPage.processPage.elementUrls["_CwZlwUmaEei8Md6BW_mwcw"] = ["Trello Board","web-checkers-process/capabilitypatterns/trello_board_4AABA3CF.html"];
contentPage.processPage.elementUrls["_rQ9xIMjkEdqIm8AJUZUQYg"] = ["Architect","openup/capabilitypatterns/architect_46C39EFC.html"];
contentPage.processPage.elementUrls["_XluoIESzEeiiE7_Qi20MVA"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_C70C1065.html"];
contentPage.processPage.elementUrls["_RfwvEDOvEduqsLmIADMQ9g"] = ["Test Script","openup/capabilitypatterns/test_script_5A47231D.html"];
contentPage.processPage.elementUrls["_0qxwYclgEdmt3adZL5Dmdw"] = ["Ongoing Tasks","openup/capabilitypatterns/ongoing_tasks_ACB4F513.html"];
contentPage.processPage.elementUrls["_XlwdVESzEeiiE7_Qi20MVA"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_BB66056B.html"];
contentPage.processPage.elementUrls["_eHAf4kbpEduLBN1xMBngqw"] = ["Test Case","openup/capabilitypatterns/test_case_57B5BBC9.html"];
contentPage.processPage.elementUrls["_CwOmoUmaEei8Md6BW_mwcw"] = ["Technology Stack Guideline","web-checkers-process/capabilitypatterns/technology_stack_guideline_FFD2BE83.html"];
contentPage.processPage.elementUrls["_Uc214EmZEei8Md6BW_mwcw"] = ["Development Environment Setup","web-checkers-process/capabilitypatterns/development_environment_setup_3AC598A2.html"];
contentPage.processPage.elementUrls["_PJJ3AU_dEduE1dJ2XtzzkQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_FBD42D27.html"];
contentPage.processPage.elementUrls["_DBZ2MUmaEei8Md6BW_mwcw"] = ["Test Log","web-checkers-process/capabilitypatterns/test_log_5CFD4BE9.html"];
contentPage.processPage.elementUrls["_d4GesL-FEdqb7N6KIeDL8Q"] = ["Run Developer Tests","openup/capabilitypatterns/run_developer_tests_832C8E18.html"];
contentPage.processPage.elementUrls["_y-k0bOtQEdqc1LGhiSPqRg"] = ["Plan and Manage Iteration","openup/capabilitypatterns/manage_iteration_4EF10D2F.html"];
contentPage.processPage.elementUrls["_SX4teEmZEei8Md6BW_mwcw"] = ["Code Review","web-checkers-process/capabilitypatterns/code_review_E5EF2109.html"];
contentPage.processPage.elementUrls["_C5t50UmaEei8Md6BW_mwcw"] = ["Architecture Notebook","web-checkers-process/capabilitypatterns/architecture_notebook_DD9B6723.html"];
contentPage.processPage.elementUrls["_ezOKIE9DEdudU75l2xOQTw"] = ["Analyst","openup/capabilitypatterns/analyst_1A74AEE9.html"];
contentPage.processPage.elementUrls["_hMCeQUS3EeiiE7_Qi20MVA"] = ["Inception Phase","web-checkers-process/capabilitypatterns/Inception Phase_A5F0C89F.html"];
contentPage.processPage.elementUrls["_QN4E4ALlEduHjPEP_YPH-g"] = ["Use Case","openup/capabilitypatterns/use_case_CED07C69.html"];
contentPage.processPage.elementUrls["_YUxfcESzEeiiE7_Qi20MVA"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_9E8CC6E7.html"];
contentPage.processPage.elementUrls["_bWELsd1qEduavbdP4P0fvw"] = ["Develop Solution Increment","openup/capabilitypatterns/develop_solution_436ECE62.html"];
contentPage.processPage.elementUrls["_DBadQUmaEei8Md6BW_mwcw"] = ["Test Script","web-checkers-process/capabilitypatterns/test_script_EFF8C8B0.html"];
contentPage.processPage.elementUrls["_CwTfIUmaEei8Md6BW_mwcw"] = ["Risk List","web-checkers-process/capabilitypatterns/risk_list_B8ABB17D.html"];
contentPage.processPage.elementUrls["_Y5DAML-EEdqb7N6KIeDL8Q"] = ["Work Items List","openup/capabilitypatterns/work_items_list_9DA841A8.html"];
contentPage.processPage.elementUrls["__1T74ClZEdytYo99TZh2Ng"] = ["Developer","openup/capabilitypatterns/developer_B36C868A.html"];
contentPage.processPage.elementUrls["_HTBBME_dEduE1dJ2XtzzkQ"] = ["Tester","openup/capabilitypatterns/tester_41C5AFF4.html"];
contentPage.processPage.elementUrls["_ZIYhIDlJEdyTZ9G7ByfQTw"] = ["Iteration Plan","openup/capabilitypatterns/iteration_plan_309C6824.html"];
contentPage.processPage.elementUrls["_r1QxIDeqEduCsbgJNeFsSw"] = ["Project Manager","openup/capabilitypatterns/project_manager_56901073.html"];
contentPage.processPage.elementUrls["_SX4GYkmZEei8Md6BW_mwcw"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_815C4CCE.html"];
contentPage.processPage.elementUrls["_wG28gFY6EdqI9sTOt2pjHw"] = ["Use-Case Model","openup/capabilitypatterns/uc_model_66875B44.html"];
contentPage.processPage.elementUrls["_0rilYclgEdmt3adZL5Dmdw"] = ["Test Solution","openup/capabilitypatterns/Test Solution_508027B8.html"];
contentPage.processPage.elementUrls["_HTBBMU_dEduE1dJ2XtzzkQ"] = ["Developer","openup/capabilitypatterns/developer_4C639004.html"];
contentPage.processPage.elementUrls["_BmbHQU_cEduE1dJ2XtzzkQ"] = ["Tester","openup/capabilitypatterns/tester_DED65E84.html"];
contentPage.processPage.elementUrls["_RcJd9kmZEei8Md6BW_mwcw"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_276259E1.html"];
contentPage.processPage.elementUrls["_KkyzwTzkEeir67KZWdm-8w"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_E6C3B53.html"];
contentPage.processPage.elementUrls["_DCQx0UmaEei8Md6BW_mwcw"] = ["Implementation","web-checkers-process/capabilitypatterns/implementation_3CF5D556.html"];
contentPage.processPage.elementUrls["_y-3IretQEdqc1LGhiSPqRg"] = ["Test Solution","openup/capabilitypatterns/test_solution_F0E4EA46.html"];
contentPage.processPage.elementUrls["_SX4GZEmZEei8Md6BW_mwcw"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_4CB73AC7.html"];
contentPage.processPage.elementUrls["_Uc214UmZEei8Md6BW_mwcw"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_456378B2.html"];
contentPage.processPage.elementUrls["_DCHA0UmaEei8Md6BW_mwcw"] = ["Technology Stack Guideline","web-checkers-process/capabilitypatterns/technology_stack_guideline_E8AA4B88.html"];
contentPage.processPage.elementUrls["_y-3IrutQEdqc1LGhiSPqRg"] = ["Construction Phase Iteration","openup/capabilitypatterns/construction_phase_iteration_FB82CA56.html"];
contentPage.processPage.elementUrls["_DBwbgUmaEei8Md6BW_mwcw"] = ["Risk List","web-checkers-process/capabilitypatterns/risk_list_2115E002.html"];
contentPage.processPage.elementUrls["_ClYokUmaEei8Md6BW_mwcw"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_A9FCCB4.html"];
contentPage.processPage.elementUrls["_Cw-NgUmaEei8Md6BW_mwcw"] = ["Implementation","web-checkers-process/capabilitypatterns/implementation_30235E8E.html"];
contentPage.processPage.elementUrls["_mZDP4FY5EdqI9sTOt2pjHw"] = ["Project Manager","openup/capabilitypatterns/project_manager_23170FF9.html"];
contentPage.processPage.elementUrls["_CwSRAUmaEei8Md6BW_mwcw"] = ["Work Items List","web-checkers-process/capabilitypatterns/work_items_list_9B2B2712.html"];
contentPage.processPage.elementUrls["_kF8tYDbsEduMn613sF6-Uw"] = ["Tester","openup/capabilitypatterns/tester_571011FF.html"];
contentPage.processPage.elementUrls["_nJcQ0kS3EeiiE7_Qi20MVA"] = ["Trello Board","web-checkers-process/capabilitypatterns/trello_board_21FE5EB9.html"];
contentPage.processPage.elementUrls["_ClZ2sUmaEei8Md6BW_mwcw"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_1537690E.html"];
contentPage.processPage.elementUrls["_g2XAwheDEduXJrZWmtC8tg"] = ["Glossary","openup/capabilitypatterns/glossary_9A03A599.html"];
contentPage.processPage.elementUrls["_CxH-gUmaEei8Md6BW_mwcw"] = ["Test Script","web-checkers-process/capabilitypatterns/test_script_27D75633.html"];
contentPage.processPage.elementUrls["_RcJd8EmZEei8Md6BW_mwcw"] = ["Elaboration Phase Iteration","web-checkers-process/capabilitypatterns/Elaboration Phase Iteration_6999839C.html"];
contentPage.processPage.elementUrls["_Uc215EmZEei8Md6BW_mwcw"] = ["Team Allocation","web-checkers-process/capabilitypatterns/team_allocation_FF577AC1.html"];
contentPage.processPage.elementUrls["_TAVx0CliEdqjQsaFX0CJTw"] = ["Ongoing Tasks","openup/capabilitypatterns/ongoing_tasks_7DF42BFF.html"];
contentPage.processPage.elementUrls["_0pJ_xslgEdmt3adZL5Dmdw"] = ["Ongoing Tasks","openup/capabilitypatterns/ongoing_tasks_91569239.html"];
contentPage.processPage.elementUrls["_RcKFBEmZEei8Md6BW_mwcw"] = ["Build Sprint Demo","web-checkers-process/capabilitypatterns/build_sprint_demo_E4F6BA93.html"];
contentPage.processPage.elementUrls["_ns1RwES3EeiiE7_Qi20MVA"] = ["Create documentation and Perform Spikes","web-checkers-process/capabilitypatterns/create_documentation_and_perform_spikes_41CAF608.html"];
contentPage.processPage.elementUrls["_0Spa4BOKEduCNqgZdt_OaA"] = ["Elaboration Iteration [1..n]","openup/deliveryprocesses/elaboration_phase_iteration_427C4DE0.html"];
contentPage.processPage.elementUrls["_SX5UgEmZEei8Md6BW_mwcw"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_6F12E547.html"];
contentPage.processPage.elementUrls["_m_gdUMWrEduoutjwLchi0g"] = ["Build","openup/capabilitypatterns/build_4E0FC635.html"];
contentPage.processPage.elementUrls["_ClgkYUmaEei8Md6BW_mwcw"] = ["Code Metrics","web-checkers-process/capabilitypatterns/code_metrics_AC8E18B4.html"];
contentPage.processPage.elementUrls["_ns3G8ES3EeiiE7_Qi20MVA"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_DAD5C9DA.html"];
contentPage.processPage.elementUrls["_Uc4EAkmZEei8Md6BW_mwcw"] = ["Transistion Phase Iteration","web-checkers-process/capabilitypatterns/Transistion Phase Iteration_FF8582D.html"];
contentPage.processPage.elementUrls["_Cw9mcUmaEei8Md6BW_mwcw"] = ["Developer Test","web-checkers-process/capabilitypatterns/developer_test_E113B8E5.html"];
contentPage.processPage.elementUrls["_F6WiEMEQEduTGJ8i4u8TMw"] = ["Architect","openup/capabilitypatterns/architect_5794F10E.html"];
contentPage.processPage.elementUrls["_0pWNA8lgEdmt3adZL5Dmdw"] = ["Initiate Project","openup/capabilitypatterns/initiate_project_D9C03857.html"];
contentPage.processPage.elementUrls["_wGw14FY6EdqI9sTOt2pjHw"] = ["Vision","openup/capabilitypatterns/vision_C6D6A6B.html"];
contentPage.processPage.elementUrls["_BgndgTzkEeir67KZWdm-8w"] = ["Construction Phase","web-checkers-process/capabilitypatterns/Construction Phase_379E171D.html"];
contentPage.processPage.elementUrls["_DCDWcUmaEei8Md6BW_mwcw"] = ["Github Repository","web-checkers-process/capabilitypatterns/github_repository_1FD764CF.html"];
contentPage.processPage.elementUrls["_vAmGIL-EEdqb7N6KIeDL8Q"] = ["Refine the Architecture","openup/capabilitypatterns/refine_the_architecture_4A9BFEF8.html"];
contentPage.processPage.elementUrls["_cMHeAb-FEdqb7N6KIeDL8Q"] = ["Architecture Notebook","openup/capabilitypatterns/architecture_notebook_A9538D79.html"];
contentPage.processPage.elementUrls["_C5MVYUmaEei8Md6BW_mwcw"] = ["Team Information","web-checkers-process/capabilitypatterns/team_information_92478F82.html"];
contentPage.processPage.elementUrls["_Uc4EBkmZEei8Md6BW_mwcw"] = ["README and User Guide","web-checkers-process/capabilitypatterns/readme_and_user_guide_D48A3A4C.html"];
contentPage.processPage.elementUrls["_Uc3c_EmZEei8Md6BW_mwcw"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_522F81E8.html"];
contentPage.processPage.elementUrls["_-Y3UcFY4EdqI9sTOt2pjHw"] = ["Developer Test","openup/capabilitypatterns/developer_test_D491389E.html"];
contentPage.processPage.elementUrls["_mZt-QFY5EdqI9sTOt2pjHw"] = ["Project Plan","openup/capabilitypatterns/project_plan_B7AA81E9.html"];
contentPage.processPage.elementUrls["_ClhLcUmaEei8Md6BW_mwcw"] = ["Final Release","web-checkers-process/capabilitypatterns/final_release_5A40EDEA.html"];
contentPage.processPage.elementUrls["_0o3r4slgEdmt3adZL5Dmdw"] = ["Inception Phase Iteration","openup/capabilitypatterns/inception_phase_iteration_C2188B46.html"];
contentPage.processPage.elementUrls["_eHAf4UbpEduLBN1xMBngqw"] = ["Tester","openup/capabilitypatterns/tester_691CA7B3.html"];
contentPage.processPage.elementUrls["_RLSqYESqEeiiE7_Qi20MVA"] = ["Create Architecture Documents","web-checkers-process/capabilitypatterns/create_architecture_documents_508B116.html"];
contentPage.processPage.elementUrls["_SX4GY0mZEei8Md6BW_mwcw"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_EA362293.html"];
contentPage.processPage.elementUrls["_SX4GaUmZEei8Md6BW_mwcw"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_B75249B0.html"];
contentPage.processPage.elementUrls["_C4rYAUmaEei8Md6BW_mwcw"] = ["Project Plan","web-checkers-process/capabilitypatterns/project_plan_FB648817.html"];
contentPage.processPage.elementUrls["_aX_7cESzEeiiE7_Qi20MVA"] = ["Develope Final Presentation","web-checkers-process/capabilitypatterns/develope_final_presentation_976F9AAC.html"];
contentPage.processPage.elementUrls["_J8-00MAZEdqX-s4mWhkyqQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_D553728A.html"];
contentPage.processPage.elementUrls["_DCPjsUmaEei8Md6BW_mwcw"] = ["Developer Test","web-checkers-process/capabilitypatterns/developer_test_8830D486.html"];
contentPage.processPage.elementUrls["_C4-6AUmaEei8Md6BW_mwcw"] = ["Test Script","web-checkers-process/capabilitypatterns/test_script_6E7A6319.html"];
contentPage.processPage.elementUrls["_Uc3c_0mZEei8Md6BW_mwcw"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_B4404BD3.html"];
contentPage.processPage.elementUrls["_DT8oATk-EduFTqg5hiiQIw"] = ["Architect","openup/capabilitypatterns/architect_A67530D.html"];
contentPage.processPage.elementUrls["_SX4tcUmZEei8Md6BW_mwcw"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_67693CDB.html"];
contentPage.processPage.elementUrls["_RuT34ESqEeiiE7_Qi20MVA"] = ["Developer","web-checkers-process/capabilitypatterns/developer_B8D07DE5.html"];
contentPage.processPage.elementUrls["_oSQYEL3SEdqfrv3k16plXw"] = ["Test Log","openup/capabilitypatterns/test_log_C5FF02E2.html"];
contentPage.processPage.elementUrls["_RcKFAkmZEei8Md6BW_mwcw"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_199BCC9A.html"];
contentPage.processPage.elementUrls["_Uc4ECUmZEei8Md6BW_mwcw"] = ["Final Release","web-checkers-process/capabilitypatterns/final_release_AA830855.html"];
contentPage.processPage.elementUrls["_XluoIUSzEeiiE7_Qi20MVA"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_D1A9F075.html"];
contentPage.processPage.elementUrls["_uknUwL-EEdqb7N6KIeDL8Q"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_4E585C02.html"];
contentPage.processPage.elementUrls["_Uc4EAUmZEei8Md6BW_mwcw"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_215F4417.html"];
contentPage.processPage.elementUrls["_VJjgoUSzEeiiE7_Qi20MVA"] = ["Transistion Phase","web-checkers-process/capabilitypatterns/Transistion Phase_E4AE2C92.html"];
contentPage.processPage.elementUrls["_C5R08UmaEei8Md6BW_mwcw"] = ["Design","web-checkers-process/capabilitypatterns/design_3A5816B8.html"];
contentPage.processPage.elementUrls["_I7M_wTzkEeir67KZWdm-8w"] = ["Tester","web-checkers-process/capabilitypatterns/tester_F185C032.html"];
contentPage.processPage.elementUrls["_YUw4YESzEeiiE7_Qi20MVA"] = ["Create Final Design Document","web-checkers-process/capabilitypatterns/create_final_design_document_DDF103A0.html"];
contentPage.processPage.elementUrls["_DBYoEUmaEei8Md6BW_mwcw"] = ["Test Case","web-checkers-process/capabilitypatterns/test_case_5265AF8F.html"];
contentPage.processPage.elementUrls["_CwS4EUmaEei8Md6BW_mwcw"] = ["Project Plan","web-checkers-process/capabilitypatterns/project_plan_937B3AF0.html"];
contentPage.processPage.elementUrls["_dAoEIL-FEdqb7N6KIeDL8Q"] = ["Implement the Solution","openup/capabilitypatterns/implement_solution_62FF3347.html"];
contentPage.processPage.elementUrls["_kFwgIDbsEduMn613sF6-Uw"] = ["Create Test Cases","openup/capabilitypatterns/create_test_cases_9D1EBAA3.html"];
contentPage.processPage.elementUrls["_SX4tckmZEei8Md6BW_mwcw"] = ["Tester","web-checkers-process/capabilitypatterns/tester_560250F1.html"];
contentPage.processPage.elementUrls["_Cwj90UmaEei8Md6BW_mwcw"] = ["Architecture Notebook","web-checkers-process/capabilitypatterns/architecture_notebook_4761D9B3.html"];
contentPage.processPage.elementUrls["_DCFysUmaEei8Md6BW_mwcw"] = ["Team Information","web-checkers-process/capabilitypatterns/team_information_88DA2F1F.html"];
contentPage.processPage.elementUrls["_RcKsEkmZEei8Md6BW_mwcw"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_52D68403.html"];
contentPage.processPage.elementUrls["_C4wQgUmaEei8Md6BW_mwcw"] = ["README and User Guide","web-checkers-process/capabilitypatterns/readme_and_user_guide_41E23A84.html"];
contentPage.processPage.elementUrls["_SX4tc0mZEei8Md6BW_mwcw"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_BEDC26B6.html"];
contentPage.processPage.elementUrls["_oR39mb3SEdqfrv3k16plXw"] = ["Run Tests","openup/capabilitypatterns/run_tests_84871F0D.html"];
contentPage.processPage.elementUrls["_Y1-IAkSzEeiiE7_Qi20MVA"] = ["README and User Guide","web-checkers-process/capabilitypatterns/readme_and_user_guide_8E2A4C19.html"];
contentPage.processPage.elementUrls["_mKmV0L-EEdqb7N6KIeDL8Q"] = ["Vision","openup/capabilitypatterns/vision_E89EABB3.html"];
contentPage.processPage.elementUrls["_CmOWEUmaEei8Md6BW_mwcw"] = ["Risk List","web-checkers-process/capabilitypatterns/risk_list_9545A7CD.html"];
contentPage.processPage.elementUrls["_Cw0cgUmaEei8Md6BW_mwcw"] = ["Team Information","web-checkers-process/capabilitypatterns/team_information_C602E680.html"];
contentPage.processPage.elementUrls["_Uc216UmZEei8Md6BW_mwcw"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_CE873CF0.html"];
contentPage.processPage.elementUrls["_CwXJgUmaEei8Md6BW_mwcw"] = ["Slack Team","web-checkers-process/capabilitypatterns/slack_team_E1A8D97F.html"];
contentPage.processPage.elementUrls["_9kUSEFY4EdqI9sTOt2pjHw"] = ["Developer","openup/capabilitypatterns/developer_24A8709E.html"];
contentPage.processPage.elementUrls["_0oreoclgEdmt3adZL5Dmdw"] = ["Agree on the Technical Approach","openup/capabilitypatterns/agree_technical_approach_944692EF.html"];
contentPage.processPage.elementUrls["_NXkrwcWpEduoutjwLchi0g"] = ["Use Case","openup/capabilitypatterns/use_case_DFCA7029.html"];
contentPage.processPage.elementUrls["_ZRfVYL-EEdqb7N6KIeDL8Q"] = ["Detail Requirements","openup/capabilitypatterns/detail_requirements_6AD0E2CB.html"];
contentPage.processPage.elementUrls["_DCD9gUmaEei8Md6BW_mwcw"] = ["Requirement Document","web-checkers-process/capabilitypatterns/requirement_document_182778AD.html"];
contentPage.processPage.elementUrls["_86w-oOB4EdqnKu908IEluw"] = ["Glossary","openup/capabilitypatterns/glossary_2966685C.html"];
contentPage.processPage.elementUrls["_RuVGAESqEeiiE7_Qi20MVA"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_94CC494A.html"];
contentPage.processPage.elementUrls["_9k_AcFY4EdqI9sTOt2pjHw"] = ["Design","openup/capabilitypatterns/design_C4187064.html"];
contentPage.processPage.elementUrls["_mZVjwFY5EdqI9sTOt2pjHw"] = ["Iteration Plan","openup/capabilitypatterns/iteration_plan_C1F43E5E.html"];
contentPage.processPage.elementUrls["_DBk1UUmaEei8Md6BW_mwcw"] = ["Slack Team","web-checkers-process/capabilitypatterns/slack_team_15A1376F.html"];
contentPage.processPage.elementUrls["_DBnRkUmaEei8Md6BW_mwcw"] = ["Trello Board","web-checkers-process/capabilitypatterns/trello_board_3406C317.html"];
contentPage.processPage.elementUrls["_SX3fUkmZEei8Md6BW_mwcw"] = ["Create Documentation","web-checkers-process/capabilitypatterns/create_documentation_6F14C452.html"];
contentPage.processPage.elementUrls["_31E_YBOKEduCNqgZdt_OaA"] = ["Initial Operational Capability Milestone","openup/deliveryprocesses/initial_operational_capability_F4ECB9F.html"];
contentPage.processPage.elementUrls["_I7Nm0DzkEeir67KZWdm-8w"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_89655876.html"];
contentPage.processPage.elementUrls["_C49E0UmaEei8Md6BW_mwcw"] = ["Test Case","web-checkers-process/capabilitypatterns/test_case_495C25CD.html"];
contentPage.processPage.elementUrls["_DBjAIUmaEei8Md6BW_mwcw"] = ["Architecture Notebook","web-checkers-process/capabilitypatterns/architecture_notebook_D1CEE3AC.html"];
contentPage.processPage.elementUrls["_SX4GZkmZEei8Md6BW_mwcw"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_45EE2EED.html"];
contentPage.processPage.elementUrls["_ns2f4US3EeiiE7_Qi20MVA"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_D32C216E.html"];
contentPage.processPage.elementUrls["_RcKFAUmZEei8Md6BW_mwcw"] = ["Architect","web-checkers-process/capabilitypatterns/architect_2B02B884.html"];
contentPage.processPage.elementUrls["_CmMg4UmaEei8Md6BW_mwcw"] = ["Work Items List","web-checkers-process/capabilitypatterns/work_items_list_92F81310.html"];
contentPage.processPage.elementUrls["_Uc216kmZEei8Md6BW_mwcw"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_BD205106.html"];
contentPage.processPage.elementUrls["_Uc3c-UmZEei8Md6BW_mwcw"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_F84F37EA.html"];
contentPage.processPage.elementUrls["_ezOKIU9DEdudU75l2xOQTw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_25128EF9.html"];
contentPage.processPage.elementUrls["_Uc219EmZEei8Md6BW_mwcw"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_119F033D.html"];
contentPage.processPage.elementUrls["_Uc218kmZEei8Md6BW_mwcw"] = ["Trello Board","web-checkers-process/capabilitypatterns/trello_board_46441544.html"];
contentPage.processPage.elementUrls["_lqbA8L-EEdqb7N6KIeDL8Q"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_926E3848.html"];
contentPage.processPage.elementUrls["_RuT34USqEeiiE7_Qi20MVA"] = ["Tester","web-checkers-process/capabilitypatterns/tester_C36E5DF5.html"];
contentPage.processPage.elementUrls["_YUw4YkSzEeiiE7_Qi20MVA"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_D727F7C6.html"];
contentPage.processPage.elementUrls["_mz9wEES3EeiiE7_Qi20MVA"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_A5A49BBF.html"];
contentPage.processPage.elementUrls["_nykLZL3SEdqfrv3k16plXw"] = ["Implement Test Scripts","openup/capabilitypatterns/implement_test_scripts_52EE14CD.html"];
contentPage.processPage.elementUrls["_CwRp8UmaEei8Md6BW_mwcw"] = ["Iteration Plan","web-checkers-process/capabilitypatterns/iteration_plan_E45FD23A.html"];
contentPage.processPage.elementUrls["_Xrrj0ASqEdy6Meh4O3uDnA"] = ["Developer","openup/capabilitypatterns/developer_600F7DE6.html"];
contentPage.processPage.elementUrls["_nJcQ0ES3EeiiE7_Qi20MVA"] = ["Github Repository","web-checkers-process/capabilitypatterns/github_repository_28C76A93.html"];
contentPage.processPage.elementUrls["_SHoW0ESqEeiiE7_Qi20MVA"] = ["Build Sprint Demo","web-checkers-process/capabilitypatterns/build_sprint_demo_5032E384.html"];
contentPage.processPage.elementUrls["_Y1-IAUSzEeiiE7_Qi20MVA"] = ["Technology Specialist","web-checkers-process/capabilitypatterns/technology_specialist_9F913803.html"];
contentPage.processPage.elementUrls["_RLUfkkSqEeiiE7_Qi20MVA"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_C97304DD.html"];
contentPage.processPage.elementUrls["_C4r_EUmaEei8Md6BW_mwcw"] = ["Risk List","web-checkers-process/capabilitypatterns/risk_list_DFAA5B19.html"];
contentPage.processPage.elementUrls["_HTpzcDSLEdursMWmT1aZyw"] = ["Use-Case Model","openup/capabilitypatterns/uc_model_B482FAAF.html"];
contentPage.processPage.elementUrls["_oNJDsFY5EdqI9sTOt2pjHw"] = ["Manage Iteration","openup/capabilitypatterns/manage_iteration_C2AC19FA.html"];
contentPage.processPage.elementUrls["_Uc3c9EmZEei8Md6BW_mwcw"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_2487F14E.html"];
contentPage.processPage.elementUrls["_ns4VEES3EeiiE7_Qi20MVA"] = ["Requirement Document","web-checkers-process/capabilitypatterns/requirement_document_CADBD61B.html"];
contentPage.processPage.elementUrls["_Uc2150mZEei8Md6BW_mwcw"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_616844AC.html"];
contentPage.processPage.elementUrls["_467NIhOKEduCNqgZdt_OaA"] = ["Transition Iteration [1..n]","openup/deliveryprocesses/transition_phase_iteration_31BFECF6.html"];
contentPage.processPage.elementUrls["_RLT4gkSqEeiiE7_Qi20MVA"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_A4428E50.html"];
contentPage.processPage.elementUrls["_Uc3c80mZEei8Md6BW_mwcw"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_C206D91A.html"];
contentPage.processPage.elementUrls["_CxGwYUmaEei8Md6BW_mwcw"] = ["Test Log","web-checkers-process/capabilitypatterns/test_log_F37B63EC.html"];
contentPage.processPage.elementUrls["_PJJ3AE_dEduE1dJ2XtzzkQ"] = ["Analyst","openup/capabilitypatterns/analyst_F1364D17.html"];
contentPage.processPage.elementUrls["_0sx7islgEdmt3adZL5Dmdw"] = ["Develop the Architecture","openup/capabilitypatterns/develop_architecture_AF0A71D5.html"];
contentPage.processPage.elementUrls["_RLUfkUSqEeiiE7_Qi20MVA"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_DAD9F0C7.html"];
contentPage.processPage.elementUrls["_SX4tcEmZEei8Md6BW_mwcw"] = ["Developer","web-checkers-process/capabilitypatterns/developer_5CCB5CCB.html"];
contentPage.processPage.elementUrls["_h2-iAfimEdmugcVr9AdHjQ"] = ["Develop Solution Increment","openup/capabilitypatterns/develop_solution_633E2E80.html"];
contentPage.processPage.elementUrls["_qQppAFY4EdqI9sTOt2pjHw"] = ["Architecture Notebook","openup/capabilitypatterns/architecture_notebook_F2777AB2.html"];
contentPage.processPage.elementUrls["_C5l-AUmaEei8Md6BW_mwcw"] = ["Technology Stack Guideline","web-checkers-process/capabilitypatterns/technology_stack_guideline_40E9AA32.html"];
contentPage.processPage.elementUrls["_I7M_wjzkEeir67KZWdm-8w"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_E01ED448.html"];
contentPage.processPage.elementUrls["_RcJd8kmZEei8Md6BW_mwcw"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_62D077C2.html"];
contentPage.processPage.elementUrls["_ns48IES3EeiiE7_Qi20MVA"] = ["Technology Cheet Sheet","web-checkers-process/capabilitypatterns/technology_cheet_sheet_C32BE9F9.html"];
contentPage.processPage.elementUrls["_Uc3c9UmZEei8Md6BW_mwcw"] = ["Architect","web-checkers-process/capabilitypatterns/architect_2F25D15E.html"];
contentPage.processPage.elementUrls["_C4qw8UmaEei8Md6BW_mwcw"] = ["Work Items List","web-checkers-process/capabilitypatterns/work_items_list_4499333F.html"];
contentPage.processPage.elementUrls["_KkyzwjzkEeir67KZWdm-8w"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_FD054F69.html"];
contentPage.processPage.elementUrls["_nJcQ0US3EeiiE7_Qi20MVA"] = ["Slack Team","web-checkers-process/capabilitypatterns/slack_team_33654AA3.html"];
contentPage.processPage.elementUrls["_CwNYgUmaEei8Md6BW_mwcw"] = ["Technology Cheet Sheet","web-checkers-process/capabilitypatterns/technology_cheet_sheet_E2523418.html"];
contentPage.processPage.elementUrls["_I7Nm0zzkEeir67KZWdm-8w"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_8D3A2CAC.html"];
contentPage.processPage.elementUrls["_0ruyoclgEdmt3adZL5Dmdw"] = ["Identify and Refine Requirements","openup/capabilitypatterns/identify_and_refine_requirements_824699A3.html"];
contentPage.processPage.elementUrls["_CwUGMUmaEei8Md6BW_mwcw"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_CAF339F9.html"];
contentPage.processPage.elementUrls["_3CqrAROKEduCNqgZdt_OaA"] = ["Construction Iteration [1..n]","openup/deliveryprocesses/construction_phase_iteration_A276D580.html"];
contentPage.processPage.elementUrls["_cL1KIL-FEdqb7N6KIeDL8Q"] = ["Design the Solution","openup/capabilitypatterns/design_solution_1FD864B7.html"];
contentPage.processPage.elementUrls["_Uc4EBUmZEei8Md6BW_mwcw"] = ["Conduct Final Reviews","web-checkers-process/capabilitypatterns/conduct_final_reviews_E5F12636.html"];
contentPage.processPage.elementUrls["_0o9ygclgEdmt3adZL5Dmdw"] = ["Identify and Refine Requirements","openup/capabilitypatterns/identify_and_refine_requirements_EDFE69E4.html"];
contentPage.processPage.elementUrls["_XlwdU0SzEeiiE7_Qi20MVA"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_58E4ED37.html"];
contentPage.processPage.elementUrls["_SZOIoEmSEduO0bs89Khm8Q"] = ["Architecture Notebook","openup/capabilitypatterns/architecture_notebook_8F24FBFC.html"];
contentPage.processPage.elementUrls["_0okw8clgEdmt3adZL5Dmdw"] = ["Identify and Refine Requirements","openup/capabilitypatterns/identify_and_refine_requirements_797D013F.html"];
contentPage.processPage.elementUrls["_flCL8AirEdySCYtHvCR6bg"] = ["Test Log","openup/capabilitypatterns/test_log_53CD6379.html"];
contentPage.processPage.elementUrls["_Uc215UmZEei8Md6BW_mwcw"] = ["Create documentation and Perform Spikes","web-checkers-process/capabilitypatterns/create_documentation_and_perform_spikes_9F55AD1.html"];
contentPage.processPage.elementUrls["_nen3UexwEduRmOwej6Grog"] = ["Develop Solution Increment","openup/capabilitypatterns/develop_solution_4DCE9885.html"];
contentPage.processPage.elementUrls["_LKGgQTzkEeir67KZWdm-8w"] = ["Architect","web-checkers-process/capabilitypatterns/architect_52EA9557.html"];
contentPage.processPage.elementUrls["_5LsMUFY1EdqI9sTOt2pjHw"] = ["Request Change","openup/capabilitypatterns/request_change_1290834C.html"];
contentPage.processPage.elementUrls["_6QwpgQ1SEdyKD8XBf_Hbrw"] = ["Implementation","openup/capabilitypatterns/implementation_23DE2C46.html"];
contentPage.processPage.elementUrls["_Clc6AUmaEei8Md6BW_mwcw"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_C134F5B.html"];
contentPage.processPage.elementUrls["_XKDWIFY5EdqI9sTOt2pjHw"] = ["Plan Project","openup/capabilitypatterns/plan_the_project_1CC89731.html"];
contentPage.processPage.elementUrls["_CliZkUmaEei8Md6BW_mwcw"] = ["README and User Guide","web-checkers-process/capabilitypatterns/readme_and_user_guide_A5C32DCF.html"];
contentPage.processPage.elementUrls["_PJJ3A0_dEduE1dJ2XtzzkQ"] = ["Project Manager","openup/capabilitypatterns/project_manager_53471702.html"];
contentPage.processPage.elementUrls["_XKbwoFY5EdqI9sTOt2pjHw"] = ["Project Plan","openup/capabilitypatterns/project_plan_24B37F0D.html"];
contentPage.processPage.elementUrls["_I7M_wDzkEeir67KZWdm-8w"] = ["Developer","web-checkers-process/capabilitypatterns/developer_E6E7E022.html"];
contentPage.processPage.elementUrls["_4x060FY1EdqI9sTOt2pjHw"] = ["Any Role","openup/capabilitypatterns/any_role_3395692A.html"];
contentPage.processPage.elementUrls["_Uc3c8EmZEei8Md6BW_mwcw"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_5FF60F2F.html"];
contentPage.processPage.elementUrls["_Y1-IAESzEeiiE7_Qi20MVA"] = ["Deploy the application","web-checkers-process/capabilitypatterns/deploy_the_application_94F357F3.html"];
contentPage.processPage.elementUrls["_DT8oAzk-EduFTqg5hiiQIw"] = ["Developer","openup/capabilitypatterns/developer_39E4733.html"];
contentPage.processPage.elementUrls["_a_F1YFY2EdqI9sTOt2pjHw"] = ["Test Script","openup/capabilitypatterns/test_script_56F46221.html"];
contentPage.processPage.elementUrls["_Uc218EmZEei8Md6BW_mwcw"] = ["Technology Cheet Sheet","web-checkers-process/capabilitypatterns/technology_cheet_sheet_4D0D211E.html"];
contentPage.processPage.elementUrls["_DBumUUmaEei8Md6BW_mwcw"] = ["Work Items List","web-checkers-process/capabilitypatterns/work_items_list_55E28061.html"];
contentPage.processPage.elementUrls["_KkyzwzzkEeir67KZWdm-8w"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_7A32F79.html"];
contentPage.processPage.elementUrls["_C5Qm0UmaEei8Md6BW_mwcw"] = ["Build","web-checkers-process/capabilitypatterns/build_2FC07A5E.html"];
contentPage.processPage.elementUrls["_oNnk0FY5EdqI9sTOt2pjHw"] = ["Work Items List","openup/capabilitypatterns/work_items_list_3834F5A0.html"];
contentPage.processPage.elementUrls["_jLaKwP77Edm1zMZYtD3GjA"] = ["Plan and Manage Iteration","openup/capabilitypatterns/manage_iteration_E0BEBBF4.html"];
contentPage.processPage.elementUrls["_nJbpwES3EeiiE7_Qi20MVA"] = ["Technology Stack Guideline","web-checkers-process/capabilitypatterns/technology_stack_guideline_AD3D212C.html"];
contentPage.processPage.elementUrls["_RcKsEEmZEei8Md6BW_mwcw"] = ["Create Architecture Documents","web-checkers-process/capabilitypatterns/create_architecture_documents_599F8FDD.html"];
contentPage.processPage.elementUrls["_CladwUmaEei8Md6BW_mwcw"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_A832E5D5.html"];
contentPage.processPage.elementUrls["_Uc216EmZEei8Md6BW_mwcw"] = ["Github Repository","web-checkers-process/capabilitypatterns/github_repository_C3E95CE0.html"];
contentPage.processPage.elementUrls["_RuUe8ESqEeiiE7_Qi20MVA"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_DE00F472.html"];
contentPage.processPage.elementUrls["_KFj6EDzkEeir67KZWdm-8w"] = ["Code Review","web-checkers-process/capabilitypatterns/code_review_99772EBB.html"];
contentPage.processPage.elementUrls["_0qrpwslgEdmt3adZL5Dmdw"] = ["Test Solution","openup/capabilitypatterns/test_solution_B2F7A244.html"];
contentPage.processPage.elementUrls["_CwV7YUmaEei8Md6BW_mwcw"] = ["Final Release","web-checkers-process/capabilitypatterns/final_release_EC58DBC.html"];
contentPage.processPage.elementUrls["_DCO8oUmaEei8Md6BW_mwcw"] = ["Design","web-checkers-process/capabilitypatterns/design_63005DF9.html"];
contentPage.processPage.elementUrls["_y1uwgBOKEduCNqgZdt_OaA"] = ["Lifecycle Objectives Milestone","openup/deliveryprocesses/lifecycle_objectives_4E2B8CB3.html"];
contentPage.processPage.elementUrls["_Cw8YUEmaEei8Md6BW_mwcw"] = ["Build","web-checkers-process/capabilitypatterns/build_1D8A01B0.html"];
contentPage.processPage.elementUrls["_Uc2140mZEei8Md6BW_mwcw"] = ["Inception Phase Iteration","web-checkers-process/capabilitypatterns/Inception Phase Iteration_9CD6628D.html"];
contentPage.processPage.elementUrls["_aVdK4APYEdyB4pp30pbnFA"] = ["Work Items List","openup/capabilitypatterns/work_items_list_7F9A369F.html"];
contentPage.processPage.elementUrls["_0sTaYMlgEdmt3adZL5Dmdw"] = ["Elaboration Phase Iteration","openup/capabilitypatterns/elaboration_phase_iteration_97E7400D.html"];
contentPage.processPage.elementUrls["_aX_7cUSzEeiiE7_Qi20MVA"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_A20D7ABC.html"];
contentPage.processPage.elementUrls["_YUxfckSzEeiiE7_Qi20MVA"] = ["User Story","web-checkers-process/capabilitypatterns/user_story_97C3BB0D.html"];
contentPage.processPage.elementUrls["_Xr0twgSqEdy6Meh4O3uDnA"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_2EAAB5B1.html"];
contentPage.processPage.elementUrls["_5v0NwBOKEduCNqgZdt_OaA"] = ["Product Release Milestone","openup/deliveryprocesses/product_release_E215D8A8.html"];
contentPage.processPage.elementUrls["_ny2fQL3SEdqfrv3k16plXw"] = ["Build","openup/capabilitypatterns/build_BA125429.html"];
contentPage.processPage.elementUrls["_Uc3c-EmZEei8Md6BW_mwcw"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_EDB157DA.html"];
contentPage.processPage.elementUrls["_C4qJ4UmaEei8Md6BW_mwcw"] = ["Iteration Plan","web-checkers-process/capabilitypatterns/iteration_plan_B5E7BD6.html"];
contentPage.processPage.elementUrls["_DBmDcUmaEei8Md6BW_mwcw"] = ["Technology Cheet Sheet","web-checkers-process/capabilitypatterns/technology_cheet_sheet_E8848332.html"];
contentPage.processPage.elementUrls["_aX_7ckSzEeiiE7_Qi20MVA"] = ["Sprint Demos","web-checkers-process/capabilitypatterns/sprint_demos_90A68ED2.html"];
contentPage.processPage.elementUrls["_Uc2170mZEei8Md6BW_mwcw"] = ["Architect","web-checkers-process/capabilitypatterns/architect_EA8C08EA.html"];
contentPage.processPage.elementUrls["_ONfJkUmZEei8Md6BW_mwcw"] = ["Web Checkers Process","web-checkers-process/capabilitypatterns/Web Checkers Process_738FA131.html"];
contentPage.processPage.elementUrls["_Uc3c_UmZEei8Md6BW_mwcw"] = ["Deploy the application","web-checkers-process/capabilitypatterns/deploy_the_application_5CCD61F8.html"];
contentPage.processPage.elementUrls["_eGoFY0bpEduLBN1xMBngqw"] = ["Work Items List","openup/capabilitypatterns/work_items_list_6D4977A.html"];
contentPage.processPage.elementUrls["_C4xeoUmaEei8Md6BW_mwcw"] = ["Technology Cheet Sheet","web-checkers-process/capabilitypatterns/technology_cheet_sheet_5F62C4EF.html"];
contentPage.processPage.elementUrls["_SHo94ESqEeiiE7_Qi20MVA"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_4882F762.html"];
contentPage.processPage.elementUrls["_Uc3c8UmZEei8Md6BW_mwcw"] = ["Tester","web-checkers-process/capabilitypatterns/tester_6A93EF3F.html"];
contentPage.processPage.elementUrls["_0sluQslgEdmt3adZL5Dmdw"] = ["Agree on the Technical Approach","openup/capabilitypatterns/agree_technical_approach_350ADF37.html"];
contentPage.processPage.elementUrls["_BmbHQE_cEduE1dJ2XtzzkQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_D4387E74.html"];
contentPage.processPage.elementUrls["_qQROgFY4EdqI9sTOt2pjHw"] = ["Architect","openup/capabilitypatterns/architect_78315249.html"];
contentPage.processPage.elementUrls["_Clbr4UmaEei8Md6BW_mwcw"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_5CF7E6A5.html"];
contentPage.processPage.elementUrls["_ns2f4ES3EeiiE7_Qi20MVA"] = ["Architect","web-checkers-process/capabilitypatterns/architect_C88E415E.html"];
contentPage.processPage.elementUrls["_RcI24UmZEei8Md6BW_mwcw"] = ["Tester","web-checkers-process/capabilitypatterns/tester_4F06ED1F.html"];
contentPage.processPage.elementUrls["_d6Q7IVY4EdqI9sTOt2pjHw"] = ["Architecture","openup/capabilitypatterns/architecture_212F5392.html"];
contentPage.processPage.elementUrls["_RcKFB0mZEei8Md6BW_mwcw"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_4707847E.html"];
contentPage.processPage.elementUrls["_YUw4YUSzEeiiE7_Qi20MVA"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_E88EE3B0.html"];
contentPage.processPage.elementUrls["_DT8oAjk-EduFTqg5hiiQIw"] = ["Tester","openup/capabilitypatterns/tester_F9006723.html"];
contentPage.processPage.elementUrls["_nJbCsES3EeiiE7_Qi20MVA"] = ["Technology Specialist","web-checkers-process/capabilitypatterns/technology_specialist_740269C3.html"];
contentPage.processPage.elementUrls["_Y5DAMb-EEdqb7N6KIeDL8Q"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_8C4155BE.html"];
contentPage.processPage.elementUrls["_LKGgQDzkEeir67KZWdm-8w"] = ["Create Documentation","web-checkers-process/capabilitypatterns/create_documentation_484CB547.html"];
contentPage.processPage.elementUrls["_d5-nQFY4EdqI9sTOt2pjHw"] = ["Architect","openup/capabilitypatterns/architect_CB606A14.html"];
contentPage.processPage.elementUrls["_4Y1wML3JEdqfrv3k16plXw"] = ["Work Items List","openup/capabilitypatterns/work_items_list_3257BEB0.html"];
contentPage.processPage.elementUrls["_wGSUwFY6EdqI9sTOt2pjHw"] = ["Analyst","openup/capabilitypatterns/analyst_D7CF3250.html"];
contentPage.processPage.elementUrls["_79bQ4DoCEdu0yYZ2bsCXog"] = ["Define Vision","openup/capabilitypatterns/define_vision_AED53484.html"];
contentPage.processPage.elementUrls["_Xr0twQSqEdy6Meh4O3uDnA"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_4011A19B.html"];
contentPage.processPage.elementUrls["_SX4GYEmZEei8Md6BW_mwcw"] = ["Construction Phase Iteration","web-checkers-process/capabilitypatterns/Construction Phase Iteration_882558A8.html"];
contentPage.processPage.elementUrls["_SX4tdUmZEei8Md6BW_mwcw"] = ["Build Solution","web-checkers-process/capabilitypatterns/build_solution_2BFB1EFA.html"];
contentPage.processPage.elementUrls["_SX4GZ0mZEei8Md6BW_mwcw"] = ["Sprint Retrospective","web-checkers-process/capabilitypatterns/sprint_retrospective_AEC804B2.html"];
contentPage.processPage.elementUrls["_S8dNQMBFEdqSgKaj2SZBmg"] = ["Architect","openup/capabilitypatterns/architect_4A0872BF.html"];
contentPage.processPage.elementUrls["_RcKFAEmZEei8Md6BW_mwcw"] = ["Conduct Code Inspection","web-checkers-process/capabilitypatterns/conduct_code_inspection_2064D874.html"];
contentPage.processPage.elementUrls["_lqOzsL-EEdqb7N6KIeDL8Q"] = ["Outline the Architecture","openup/capabilitypatterns/outline_the_architecture_79FA3059.html"];
contentPage.processPage.elementUrls["_SX4GaEmZEei8Md6BW_mwcw"] = ["Architect","web-checkers-process/capabilitypatterns/architect_ACB469A0.html"];
contentPage.processPage.elementUrls["_PZiY4USqEeiiE7_Qi20MVA"] = ["Elaboration Phase","web-checkers-process/capabilitypatterns/Elaboration Phase_E9D21C8D.html"];
contentPage.processPage.elementUrls["_S8dNQsBFEdqSgKaj2SZBmg"] = ["Tester","openup/capabilitypatterns/tester_433F66E5.html"];
contentPage.processPage.elementUrls["_kF8tYTbsEduMn613sF6-Uw"] = ["Test Case","openup/capabilitypatterns/test_case_61ADF20F.html"];
contentPage.processPage.elementUrls["_C4yFsUmaEei8Md6BW_mwcw"] = ["Trello Board","web-checkers-process/capabilitypatterns/trello_board_71AA4D6B.html"];
contentPage.processPage.elementUrls["_SX4tdkmZEei8Md6BW_mwcw"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_1A943310.html"];
contentPage.processPage.elementUrls["_eFeO0UbpEduLBN1xMBngqw"] = ["Use Case","openup/capabilitypatterns/use_case_5616913A.html"];
contentPage.processPage.elementUrls["_XluoIkSzEeiiE7_Qi20MVA"] = ["Tester","web-checkers-process/capabilitypatterns/tester_C043048B.html"];
contentPage.processPage.elementUrls["_0rcewclgEdmt3adZL5Dmdw"] = ["Develop the Architecture","openup/capabilitypatterns/develop_architecture_4C24F4D9.html"];
contentPage.processPage.elementUrls["_WrXvwPinEdmugcVr9AdHjQ"] = ["Develop Solution Increment","openup/capabilitypatterns/develop_solution_D6782BA8.html"];
contentPage.processPage.elementUrls["_XltaAESzEeiiE7_Qi20MVA"] = ["Conduct Final Reviews","web-checkers-process/capabilitypatterns/conduct_final_reviews_7B89D080.html"];
contentPage.processPage.elementUrls["_CwynUUmaEei8Md6BW_mwcw"] = ["Github Repository","web-checkers-process/capabilitypatterns/github_repository_D73954B4.html"];
contentPage.processPage.elementUrls["_DUCuoDk-EduFTqg5hiiQIw"] = ["Risk List","openup/capabilitypatterns/risk_list_248B8AAB.html"];
contentPage.processPage.elementUrls["_RuTQ0ESqEeiiE7_Qi20MVA"] = ["Conduct Code Inspection","web-checkers-process/capabilitypatterns/conduct_code_inspection_C0806A07.html"];
contentPage.processPage.elementUrls["_RuVGAUSqEeiiE7_Qi20MVA"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_9F6A295A.html"];
contentPage.processPage.elementUrls["_Uc219kmZEei8Md6BW_mwcw"] = ["Technology Specialist","web-checkers-process/capabilitypatterns/technology_specialist_AD5F763.html"];
contentPage.processPage.elementUrls["_I7Nm0jzkEeir67KZWdm-8w"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_829C4C9C.html"];
contentPage.processPage.elementUrls["_CwXwkUmaEei8Md6BW_mwcw"] = ["README and User Guide","web-checkers-process/capabilitypatterns/readme_and_user_guide_1AE390E8.html"];
contentPage.processPage.elementUrls["_eGoFYkbpEduLBN1xMBngqw"] = ["Find and Outline Requirements","openup/capabilitypatterns/find_and_outline_requirements_9DFAC1B5.html"];
contentPage.processPage.elementUrls["_Uc4EAEmZEei8Md6BW_mwcw"] = ["Project Manager","web-checkers-process/capabilitypatterns/project_manager_16C16407.html"];
contentPage.processPage.elementUrls["_a6qBUFY2EdqI9sTOt2pjHw"] = ["Tester","openup/capabilitypatterns/tester_D0AD07C2.html"];
contentPage.processPage.elementUrls["_F6WiEcEQEduTGJ8i4u8TMw"] = ["Developer","openup/capabilitypatterns/developer_462E0524.html"];
contentPage.processPage.elementUrls["_eGoFZEbpEduLBN1xMBngqw"] = ["Supporting Requirements Specification","openup/capabilitypatterns/supporting_requirements_spec_6955AFAE.html"];
contentPage.processPage.elementUrls["_Uc4ECEmZEei8Md6BW_mwcw"] = ["Code Metrics","web-checkers-process/capabilitypatterns/code_metrics_9FE52845.html"];
contentPage.processPage.elementUrls["_xupMvxOKEduCNqgZdt_OaA"] = ["Inception Iteration [1..n]","openup/deliveryprocesses/inception_phase_iteration_648AE2DA.html"];
contentPage.processPage.elementUrls["_5M7icFY1EdqI9sTOt2pjHw"] = ["Work Items List","openup/capabilitypatterns/work_items_list_13D84957.html"];
contentPage.processPage.elementUrls["_C5TqIUmaEei8Md6BW_mwcw"] = ["Implementation","web-checkers-process/capabilitypatterns/implementation_4F8E9986.html"];
contentPage.processPage.elementUrls["_mz9JAES3EeiiE7_Qi20MVA"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_6C69E456.html"];
contentPage.processPage.elementUrls["_Uc217kmZEei8Md6BW_mwcw"] = ["Requirement Document","web-checkers-process/capabilitypatterns/requirement_document_81B23325.html"];
contentPage.processPage.elementUrls["_C5i6sUmaEei8Md6BW_mwcw"] = ["Requirement Document","web-checkers-process/capabilitypatterns/requirement_document_297FC0EC.html"];
contentPage.processPage.elementUrls["_d4k_0L-FEdqb7N6KIeDL8Q"] = ["Test Log","openup/capabilitypatterns/test_log_D1C23AD1.html"];
contentPage.processPage.elementUrls["_XlwdVkSzEeiiE7_Qi20MVA"] = ["Final Release","web-checkers-process/capabilitypatterns/final_release_B49CF991.html"];
contentPage.processPage.elementUrls["_RLT4gESqEeiiE7_Qi20MVA"] = ["Architect","web-checkers-process/capabilitypatterns/architect_AB0B9A2A.html"];
contentPage.processPage.elementUrls["_DBvNYUmaEei8Md6BW_mwcw"] = ["Project Plan","web-checkers-process/capabilitypatterns/project_plan_682A08DD.html"];
contentPage.processPage.elementUrls["_FNQcoOhOEdu1i42xOtqziw"] = ["Developer","openup/capabilitypatterns/developer_7B90AE28.html"];
contentPage.processPage.elementUrls["_PFnTkOB7EdqnKu908IEluw"] = ["Glossary","openup/capabilitypatterns/glossary_BB0E50AB.html"];
contentPage.processPage.elementUrls["_eGuMBUbpEduLBN1xMBngqw"] = ["Detail Requirements","openup/capabilitypatterns/detail_requirements_13BA0F57.html"];
contentPage.processPage.elementUrls["_SZOIoUmSEduO0bs89Khm8Q"] = ["Vision","openup/capabilitypatterns/vision_99C2DC0C.html"];
contentPage.processPage.elementUrls["_C4vpcEmaEei8Md6BW_mwcw"] = ["Slack Team","web-checkers-process/capabilitypatterns/slack_team_24FCD1F8.html"];
contentPage.processPage.elementUrls["_Uc217UmZEei8Md6BW_mwcw"] = ["Technology Stack Guideline","web-checkers-process/capabilitypatterns/technology_stack_guideline_93191F0F.html"];
contentPage.processPage.elementUrls["_XlwdUESzEeiiE7_Qi20MVA"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_F6D4234C.html"];
contentPage.processPage.elementUrls["_SHo940SqEeiiE7_Qi20MVA"] = ["Version Release","web-checkers-process/capabilitypatterns/version_release_AA93C14D.html"];
contentPage.processPage.elementUrls["_XluoI0SzEeiiE7_Qi20MVA"] = ["Analyst","web-checkers-process/capabilitypatterns/analyst_291CDA50.html"];
contentPage.processPage.elementUrls["_ns4VEUS3EeiiE7_Qi20MVA"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_D579B62B.html"];
contentPage.processPage.elementUrls["_C4tNMUmaEei8Md6BW_mwcw"] = ["Code Metrics","web-checkers-process/capabilitypatterns/code_metrics_2B2C9AFE.html"];
contentPage.processPage.elementUrls["_XKVqAFY5EdqI9sTOt2pjHw"] = ["Project Manager","openup/capabilitypatterns/project_manager_24E88681.html"];
contentPage.processPage.elementUrls["_KkyzwDzkEeir67KZWdm-8w"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_3CE5B43.html"];
contentPage.processPage.elementUrls["_Uc4EA0mZEei8Md6BW_mwcw"] = ["Stakeholder","web-checkers-process/capabilitypatterns/stakeholder_78D22DF2.html"];
contentPage.processPage.elementUrls["_I7LKkDzkEeir67KZWdm-8w"] = ["Build Solution","web-checkers-process/capabilitypatterns/build_solution_B71FCD3B.html"];
contentPage.processPage.elementUrls["_SX4GYUmZEei8Md6BW_mwcw"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_92C338B8.html"];
contentPage.processPage.elementUrls["_y_PjTOtQEdqc1LGhiSPqRg"] = ["Ongoing Tasks","openup/capabilitypatterns/ongoing_tasks_2F5F2C64.html"];
contentPage.processPage.elementUrls["_eFeO0kbpEduLBN1xMBngqw"] = ["Vision","openup/capabilitypatterns/vision_44AFA550.html"];
contentPage.processPage.elementUrls["_CwN_kUmaEei8Md6BW_mwcw"] = ["Requirement Document","web-checkers-process/capabilitypatterns/requirement_document_C698071A.html"];
contentPage.processPage.elementUrls["_XluoJESzEeiiE7_Qi20MVA"] = ["Architect","web-checkers-process/capabilitypatterns/architect_8B9DF284.html"];
contentPage.processPage.elementUrls["_RcKFA0mZEei8Md6BW_mwcw"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_8275A25F.html"];
contentPage.processPage.elementUrls["_2tHGoMAYEdqX-s4mWhkyqQ"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_1B0F1D9A.html"];
contentPage.processPage.elementUrls["_Uc3c-0mZEei8Md6BW_mwcw"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_4FC221C5.html"];
contentPage.processPage.elementUrls["_DBt_QUmaEei8Md6BW_mwcw"] = ["Iteration Plan","web-checkers-process/capabilitypatterns/iteration_plan_1CA7C8F8.html"];
contentPage.processPage.elementUrls["_0rWYIslgEdmt3adZL5Dmdw"] = ["Plan and Manage Iteration","openup/capabilitypatterns/manage_iteration_84F991D7.html"];
contentPage.processPage.elementUrls["_cnzUcL-FEdqb7N6KIeDL8Q"] = ["Implement Developer Tests","openup/capabilitypatterns/impl_developer_tests_D8C7E9A0.html"];
contentPage.processPage.elementUrls["_nJZ0kES3EeiiE7_Qi20MVA"] = ["Development Environment Setup","web-checkers-process/capabilitypatterns/development_environment_setup_CEBF6480.html"];
contentPage.processPage.elementUrls["_ClYBgUmaEei8Md6BW_mwcw"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_D165154B.html"];
contentPage.processPage.elementUrls["_a8fNUFY2EdqI9sTOt2pjHw"] = ["Test Case","openup/capabilitypatterns/test_case_99E751BB.html"];
contentPage.processPage.elementUrls["_RLUfkESqEeiiE7_Qi20MVA"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_D03C10B7.html"];
contentPage.processPage.elementUrls["_VZk0YxeDEduXJrZWmtC8tg"] = ["Glossary","openup/capabilitypatterns/glossary_2D4068DC.html"];
contentPage.processPage.elementUrls["_CwwyIUmaEei8Md6BW_mwcw"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_A77141CD.html"];
contentPage.processPage.elementUrls["_eHAf4EbpEduLBN1xMBngqw"] = ["Create Test Cases","openup/capabilitypatterns/create_test_case_5E7EC7A3.html"];
contentPage.processPage.elementUrls["_I7Nm0TzkEeir67KZWdm-8w"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_94033886.html"];
contentPage.processPage.elementUrls["_CmL50UmaEei8Md6BW_mwcw"] = ["Iteration Plan","web-checkers-process/capabilitypatterns/iteration_plan_6DC79C83.html"];
contentPage.processPage.elementUrls["_Cw8_YUmaEei8Md6BW_mwcw"] = ["Design","web-checkers-process/capabilitypatterns/design_C6DB4C2.html"];
contentPage.processPage.elementUrls["_XlwdVUSzEeiiE7_Qi20MVA"] = ["Code Metrics","web-checkers-process/capabilitypatterns/code_metrics_C603E57B.html"];
contentPage.processPage.elementUrls["_KkyzxTzkEeir67KZWdm-8w"] = ["Sprint Retrospectives","web-checkers-process/capabilitypatterns/sprint_retrospectives_D2FE1D72.html"];
contentPage.processPage.elementUrls["_hhnXEDeqEduCsbgJNeFsSw"] = ["Risk List","openup/capabilitypatterns/risk_list_3FF50D1B.html"];
contentPage.processPage.elementUrls["_AdllQFY5EdqI9sTOt2pjHw"] = ["Build","openup/capabilitypatterns/build_76876126.html"];
contentPage.processPage.elementUrls["_SZICAEmSEduO0bs89Khm8Q"] = ["Plan Iteration","openup/capabilitypatterns/plan_iteration_FD2509AA.html"];
contentPage.processPage.elementUrls["_Uc4EBEmZEei8Md6BW_mwcw"] = ["Develope Final Presentation","web-checkers-process/capabilitypatterns/develope_final_presentation_DB534626.html"];
contentPage.processPage.elementUrls["__BTFAClZEdytYo99TZh2Ng"] = ["Architect","openup/capabilitypatterns/architect_91F909FD.html"];
contentPage.processPage.elementUrls["_mz6FsES3EeiiE7_Qi20MVA"] = ["Team Allocation","web-checkers-process/capabilitypatterns/team_allocation_E3590443.html"];
contentPage.processPage.elementUrls["_VNpT0FY5EdqI9sTOt2pjHw"] = ["Analyst","openup/capabilitypatterns/analyst_6A1AA080.html"];
contentPage.processPage.elementUrls["_eGuMB0bpEduLBN1xMBngqw"] = ["Stakeholder","openup/capabilitypatterns/stakeholder_6B2CF932.html"];
contentPage.processPage.elementUrls["_Uc2180mZEei8Md6BW_mwcw"] = ["Team Information","web-checkers-process/capabilitypatterns/team_information_AF1DEB09.html"];
contentPage.processPage.elementUrls["_DCNugUmaEei8Md6BW_mwcw"] = ["Build","web-checkers-process/capabilitypatterns/build_5868C19F.html"];
contentPage.processPage.elementUrls["_os33gL3SEdqfrv3k16plXw"] = ["Work Items List","openup/capabilitypatterns/work_items_list_C83C1958.html"];
contentPage.processPage.elementUrls["_CxFiQUmaEei8Md6BW_mwcw"] = ["Test Case","web-checkers-process/capabilitypatterns/test_case_A7F92407.html"];
contentPage.processPage.elementUrls["_0uyGoMlgEdmt3adZL5Dmdw"] = ["OpenUP lifecycle","openup/deliveryprocesses/openup_lifecycle_2CB8A7DA.html"];
contentPage.processPage.elementUrls["_Uc215kmZEei8Md6BW_mwcw"] = ["Technology Specialist","web-checkers-process/capabilitypatterns/technology_specialist_F88E6EE7.html"];
contentPage.processPage.elementUrls["_ClXacUmaEei8Md6BW_mwcw"] = ["Black Box Test Document","web-checkers-process/capabilitypatterns/black_box_test_document_BF1D8CCF.html"];
contentPage.processPage.elementUrls["_C5hskUmaEei8Md6BW_mwcw"] = ["Github Repository","web-checkers-process/capabilitypatterns/github_repository_1EE82492.html"];
contentPage.processPage.elementUrls["_CwVUUUmaEei8Md6BW_mwcw"] = ["Code Metrics","web-checkers-process/capabilitypatterns/code_metrics_167579DE.html"];
contentPage.processPage.elementUrls["_Uc3c8kmZEei8Md6BW_mwcw"] = ["Unit Tests","web-checkers-process/capabilitypatterns/unit_tests_592D0355.html"];
contentPage.processPage.elementUrls["_0rQRgMlgEdmt3adZL5Dmdw"] = ["Transition Phase Iteration","openup/capabilitypatterns/transition_phase_iteration_87676AD2.html"];
contentPage.processPage.elementUrls["_KAnAYE9PEdumneEH4I4Yqg"] = ["Analyst","openup/capabilitypatterns/analyst_F0254DCC.html"];
contentPage.processPage.elementUrls["_KkyMsDzkEeir67KZWdm-8w"] = ["Sprint Retrospective","web-checkers-process/capabilitypatterns/sprint_retrospective_CA93A3DA.html"];
contentPage.processPage.elementUrls["_ntNoEA1NEdyKD8XBf_Hbrw"] = ["Integrate and Create Build","openup/capabilitypatterns/integrate_and_create_build_7C2BDD46.html"];
contentPage.processPage.elementUrls["_C49r4UmaEei8Md6BW_mwcw"] = ["Test Log","web-checkers-process/capabilitypatterns/test_log_8296DD36.html"];
contentPage.processPage.elementUrls["_YUxfcUSzEeiiE7_Qi20MVA"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_A92AA6F7.html"];
contentPage.processPage.elementUrls["_RcJd9UmZEei8Md6BW_mwcw"] = ["Design Documentation","web-checkers-process/capabilitypatterns/design_documentation_38C945CB.html"];
contentPage.processPage.elementUrls["_uknUwb-EEdqb7N6KIeDL8Q"] = ["Design","openup/capabilitypatterns/design_3CF17018.html"];
contentPage.processPage.elementUrls["_RcJd8UmZEei8Md6BW_mwcw"] = ["Software Design Diagrams","web-checkers-process/capabilitypatterns/software_design_diagrams_743763AC.html"];
contentPage.processPage.elementUrls["_16nd0BOKEduCNqgZdt_OaA"] = ["Lifecycle Architecture Milestone","openup/deliveryprocesses/lifecycle_architecture_E32228EB.html"];
contentPage.processPage.elementUrls["_r1Xe0DeqEduCsbgJNeFsSw"] = ["Use-Case Model","openup/capabilitypatterns/uc_model_361896B2.html"];
contentPage.processPage.elementUrls["_SHo94kSqEeiiE7_Qi20MVA"] = ["Presentation","web-checkers-process/capabilitypatterns/presentation_41B9EB88.html"];
contentPage.processPage.elementUrls["_0nz79clgEdmt3adZL5Dmdw"] = ["Test Solution","openup/capabilitypatterns/test_solution_59590D2E.html"];
contentPage.processPage.elementUrls["_RLT4gUSqEeiiE7_Qi20MVA"] = ["Requirements Engineer","web-checkers-process/capabilitypatterns/requirements_engineer_B5A97A3A.html"];
contentPage.processPage.elementUrls["_XlwdUUSzEeiiE7_Qi20MVA"] = ["Source Code","web-checkers-process/capabilitypatterns/source_code_172035C.html"];
contentPage.processPage.elementUrls["_Uc4ECkmZEei8Md6BW_mwcw"] = ["Create Final Design Document","web-checkers-process/capabilitypatterns/create_final_design_document_991C1C6B.html"];
contentPage.processPage.elementUrls["_Xr0twASqEdy6Meh4O3uDnA"] = ["Analyst","openup/capabilitypatterns/analyst_3573C18B.html"];
contentPage.processPage.elementUrls["_RcKsFEmZEei8Md6BW_mwcw"] = ["Developer","web-checkers-process/capabilitypatterns/developer_1E3171FC.html"];
contentPage.processPage.elementUrls["_KkyMsTzkEeir67KZWdm-8w"] = ["Any Role","web-checkers-process/capabilitypatterns/any_role_D53183EA.html"];
